<a href="https://colab.research.google.com/github/dushyanthbommana/CE888/blob/main/LAB4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv",header=None)
data.head()

   0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [3]:
print(data.shape)

(24983, 101)

In [4]:
data.describe()

                0             1    ...           99            100
count  24983.000000  24983.000000  ...  24983.000000  24983.000000
mean      72.467478     34.401435  ...     55.753357     60.138090
std       21.859600     46.707059  ...     49.237139     47.913531
min       36.000000     -9.950000  ...     -9.950000     -9.950000
25%       53.000000     -0.150000  ...      1.335000      3.930000
50%       72.000000      5.050000  ...     99.000000     99.000000
75%      100.000000     99.000000  ...     99.000000     99.000000
max      100.000000     99.000000  ...     99.000000     99.000000

[8 rows x 101 columns]

In [5]:
data.replace(99, np.NaN,inplace=True)
data.head()

     0     1     2     3     4     5    ...   95    96    97    98    99    100
0   74.0 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  100.0  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   49.0   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   48.0   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4   91.0  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 101 columns]

In [6]:
data=data.drop(data.columns[[0]], axis = 1)
data

        1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 100 columns]

In [7]:
train = data.dropna()
train.head()

     1     2     3     4     5     6    ...   95    96    97    98    99    100
1   4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
5  -6.17 -3.54  0.44 -8.50 -7.09 -4.32  ... -2.18 -3.35  0.05 -9.08 -5.05 -3.45
7   6.84  3.16  9.17 -6.21 -8.16 -1.70  ... -3.16 -3.35  2.14 -0.05  1.31  0.00
8  -3.79 -3.54 -9.42 -6.89 -8.74 -0.29  ... -0.29 -0.29 -0.29 -0.29 -3.40 -4.95
11  1.31  1.80  2.57 -2.38  0.73  0.73  ...  3.45  5.44  4.08  2.48  4.51  4.66

[5 rows x 100 columns]

In [8]:
print(train.shape)

(7200, 100)

In [9]:
test = data[data.isnull().any(axis=1)]
test.head()

    1     2     3     4     5     6    ...   95    96    97    98   99   100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN  NaN  NaN
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN  NaN  NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN  NaN  NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.8  1.6
6   NaN   NaN   NaN   NaN  8.59 -9.85  ...   NaN  2.33   NaN   NaN  NaN  NaN

[5 rows x 100 columns]

In [10]:
print(test.shape)

(17783, 100)

claculating mean of each joke , high mean implies best joke

In [11]:
avg=train.mean(axis=0)
avg

1      1.331347
2      0.708058
3      0.617204
4     -1.110300
5      0.634107
         ...
96     1.749546
97     1.875689
98     0.949315
99     0.152539
100    1.442981
Length: 100, dtype: float64

In [12]:
avg.sort_values()

58   -3.519386
16   -2.692678
44   -1.763576
57   -1.572318
74   -1.416282
        ...
32    3.343306
27    3.364735
36    3.583126
89    3.827982
50    3.927833
Length: 100, dtype: float64

50th joke is best and 58 th joke is worst

In [13]:
arr = train.values
print(arr.shape)

(7200, 100)

In [14]:
rated = np.where(~np.isnan(arr))
print(len(rated[0]), rated[1].shape)

720000 (720000,)

In [15]:
def replace(orig, percentage=0.1):
    new_data = orig.copy()
    rated = np.where(~np.isnan(new_data))
    n_rated = len(rated[0])
    idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
    new_data[rated[0][idx], rated[1][idx]] = 99
    return new_data, (rated[0][idx], rated[1][idx])

In [16]:
new_arr, idx = replace(arr, 0.1)

In [17]:
arr[idx[0][0], idx[1][0]]

3.74

In [18]:
new_arr[idx[0][0], idx[1][0]]

99.0

arr is training set , new arr is validation set

In [19]:
np.set_printoptions(precision=3)

In [20]:
new_arr = pd.DataFrame(new_arr)

In [21]:
arr=pd.DataFrame(arr)

In [22]:
n_latent_factors = 2

user_ratings = arr.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [23]:
latent_item_features

array([[0.689, 0.263],
       [0.364, 0.887],
       [0.705, 0.479],
       [0.803, 0.701],
       [0.351, 0.956],
       [0.699, 0.16 ],
       [0.575, 0.546],
       [0.242, 0.815],
       [0.86 , 0.002],
       [0.071, 0.231],
       [0.94 , 0.074],
       [0.696, 0.488],
       [0.2  , 0.226],
       [0.985, 0.792],
       [0.611, 0.98 ],
       [0.503, 0.789],
       [0.157, 0.166],
       [0.49 , 0.085],
       [0.938, 0.436],
       [0.049, 0.559],
       [0.545, 0.372],
       [0.21 , 0.576],
       [0.079, 0.306],
       [0.081, 0.53 ],
       [0.952, 0.156],
       [0.944, 0.585],
       [0.428, 0.446],
       [0.952, 0.284],
       [0.454, 0.855],
       [0.914, 0.047],
       [0.56 , 0.502],
       [0.902, 0.183],
       [0.029, 0.104],
       [0.479, 0.343],
       [0.801, 0.766],
       [0.064, 0.886],
       [0.987, 0.219],
       [0.988, 0.219],
       [0.927, 0.308],
       [0.73 , 0.353],
       [0.423, 0.76 ],
       [0.176, 0.837],
       [0.342, 0.278],
       [0.638, 0.733],
       [0.529, 0.06 ],
       [0.249, 0.181],
       [0.745, 0.436],
       [0.333, 0.4  ],
       [0.781, 0.178],
       [0.199, 0.273],
       [0.752, 0.624],
       [0.819, 0.717],
       [0.313, 0.125],
       [0.409, 0.253],
       [0.66 , 0.967],
       [0.225, 0.516],
       [0.646, 0.506],
       [0.204, 0.648],
       [0.159, 0.853],
       [0.57 , 0.684],
       [0.903, 0.966],
       [0.221, 0.932],
       [0.115, 0.229],
       [0.966, 0.972],
       [0.603, 0.65 ],
       [0.979, 0.046],
       [0.323, 0.97 ],
       [0.604, 0.703],
       [0.041, 0.794],
       [0.384, 0.014],
       [0.801, 0.83 ],
       [0.207, 0.207],
       [0.611, 0.952],
       [0.444, 0.637],
       [0.876, 0.287],
       [0.354, 0.05 ],
       [0.603, 0.343],
       [0.026, 0.369],
       [0.457, 0.883],
       [0.499, 0.541],
       [0.505, 0.222],
       [0.845, 0.473],
       [0.978, 0.027],
       [0.464, 0.731],
       [0.014, 0.538],
       [0.555, 0.631],
       [0.783, 0.89 ],
       [0.393, 0.896],
       [0.382, 0.622],
       [0.518, 0.914],
       [0.533, 0.629],
       [0.216, 0.714],
       [0.789, 0.112],
       [0.233, 0.709],
       [0.88 , 0.908],
       [0.362, 0.506],
       [0.105, 0.52 ],
       [0.646, 0.723],
       [0.333, 0.975],
       [0.56 , 0.055]])

In [24]:
latent_user_preferences

array([[0.907, 0.188],
       [0.665, 0.419],
       [0.843, 0.202],
       ...,
       [0.28 , 0.264],
       [0.145, 0.708],
       [0.829, 0.929]])

In [25]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

In [26]:
def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err

In [27]:
def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if(not np.isnan(rating) and rating!=99.00):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
num_iter = 100
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

In [29]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[1.254, 0.603, 0.721, ..., 1.005, 0.274, 1.472],
       [0.809, 0.472, 0.475, ..., 0.691, 0.25 , 0.941],
       [1.019, 0.468, 0.584, ..., 0.805, 0.203, 1.199],
       ...,
       [0.557, 0.377, 0.333, ..., 0.503, 0.217, 0.642],
       [0.913, 0.825, 0.569, ..., 0.932, 0.538, 1.03 ],
       [1.892, 1.333, 1.136, ..., 1.735, 0.785, 2.173]])

In [30]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [ ]:
comparison_data

In [32]:
movies_data= pd.read_excel('https://github.com/albanda/CE888/raw/master/lab4-recommender/movies_latent_factors.xlsx')
movies_data.head()

   Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]